<?php 
include("conexiondb.php");
if (isset($_POST['ENVIAR'])){
    $PRIMER_NOMBRE= $_POST['PRIMER_NOMBRE'];
    $SEGUNDO_NOMBRE= $_POST['SEGUNDO_NOMBRE'];
    $PRIMER_APELLIDO=$_POST['PRIMER_APELLIDO'];
    $SEGUNDO_APELLIDO=$_POST['SEGUNDO_APELLIDO'];
    $TELEFONO_CONTACTO=$_POST['TELEFONO_CONTACTO'];
    $CORREO= $_POST['CORREO'];
    $DIRECCION=$_POST['DIRECCION'];
    $NUMERO_DOCUMENTO =$_POST['NUMERO_DOCUMENTO'];
    $TIPODOCUMENTO_ID_TIPO_DOCUMENTO=$_POST['TIPODOCUMENTO_ID_TIPO_DOCUMENTO'];
    $EDAD=$_POST['EDAD'];
    $GENERO_ID_GENERO=$_POST['GENERO_ID_GENERO'];
    $DEPORTE_ID_DEPORTE=$_POST['DEPORTE_ID_DEPORTE'];

    $query ="INSERT INTO usuario(PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, 
    SEGUNDO_APELLIDO,TELEFONO_CONTACTO, CORREO, DIRECCION, NUMERO_DOCUMENTO,EDAD, TIPODOCUMENTO_ID_TIPO_DOCUMENTO,GENERO_ID_GENERO,DEPORTE_ID_DEPORTE) 
    VALUES ('$PRIMER_NOMBRE','$SEGUNDO_NOMBRE','$PRIMER_APELLIDO','$SEGUNDO_APELLIDO',
    '$TELEFONO_CONTACTO','$CORREO','$DIRECCION','$NUMERO_DOCUMENTO','$EDAD','$TIPODOCUMENTO_ID_TIPO_DOCUMENTO','$GENERO_ID_GENERO','$DEPORTE_ID_DEPORTE')";
    $result=mysqli_query($conn,$query);
    if (!$result){
        die("Query Failed");
    }
    header("location:index.php");
}

?>